"""placenames -> places

Revision ID: 05b9437cc8ba
Revises: 8f130ba1a140
Create Date: 2020-03-10 12:18:57.098754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b9437cc8ba'
down_revision = '8f130ba1a140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('place_id', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('dpt', sa.String(length=2), nullable=False),
    sa.Column('commune_insee_code', sa.String(length=5), nullable=True),
    sa.Column('localization_commune_insee_code', sa.String(length=5), nullable=True),
    sa.Column('localization_place_id', sa.String(length=10), nullable=True),
    sa.Column('localization_certainty', sa.Enum('high', 'low'), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('num_start_page', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['commune_insee_code'], ['insee_commune.insee_code'], ),
    sa.ForeignKeyConstraint(['localization_commune_insee_code'], ['insee_commune.insee_code'], ),
    sa.ForeignKeyConstraint(['localization_place_id'], ['place.place_id'], ),
    sa.PrimaryKeyConstraint('place_id')
    )
    op.create_index(op.f('ix_place_commune_insee_code'), 'place', ['commune_insee_code'], unique=False)
    op.create_index(op.f('ix_place_localization_commune_insee_code'), 'place', ['localization_commune_insee_code'], unique=False)
    op.create_index(op.f('ix_place_localization_place_id'), 'place', ['localization_place_id'], unique=False)
    op.create_index(op.f('ix_place_num_start_page'), 'place', ['num_start_page'], unique=False)
    op.create_table('place_alt_label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.String(length=10), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.place_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'label', name='_place_label_uc')
    )
    op.create_index(op.f('ix_place_alt_label_place_id'), 'place_alt_label', ['place_id'], unique=False)
    op.create_table('place_old_label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('old_label_id', sa.String(length=13), nullable=False),
    sa.Column('place_id', sa.String(length=10), nullable=False),
    sa.Column('rich_label', sa.String(length=250), nullable=False),
    sa.Column('rich_date', sa.String(length=100), nullable=True),
    sa.Column('text_date', sa.String(length=100), nullable=True),
    sa.Column('rich_reference', sa.Text(), nullable=True),
    sa.Column('rich_label_node', sa.Text(), nullable=True),
    sa.Column('text_label_node', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.place_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('old_label_id')
    )
    op.create_index(op.f('ix_place_old_label_place_id'), 'place_old_label', ['place_id'], unique=False)
    op.drop_index('ix_placename_commune_insee_code', table_name='placename')
    op.drop_index('ix_placename_localization_commune_insee_code', table_name='placename')
    op.drop_index('ix_placename_localization_placename_id', table_name='placename')
    op.drop_index('ix_placename_num_start_page', table_name='placename')
    op.drop_table('placename')
    op.drop_index('ix_placename_old_label_placename_id', table_name='placename_old_label')
    op.drop_table('placename_old_label')
    op.drop_index('ix_placename_alt_label_placename_id', table_name='placename_alt_label')
    op.drop_table('placename_alt_label')
    op.add_column('feature_type', sa.Column('place_id', sa.String(length=10), nullable=True))
    op.create_unique_constraint('_place_term_uc', 'feature_type', ['place_id', 'term'])
    op.create_index(op.f('ix_feature_type_place_id'), 'feature_type', ['place_id'], unique=False)
    op.drop_constraint('_placename_term_uc', 'feature_type', type_='unique')
    op.drop_index('ix_feature_type_placename_id', table_name='feature_type')
    op.drop_constraint(None, 'feature_type', type_='foreignkey')
    op.create_foreign_key(None, 'feature_type', 'place', ['place_id'], ['place_id'])
    op.drop_column('feature_type', 'placename_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_type', sa.Column('placename_id', sa.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'feature_type', type_='foreignkey')
    op.create_foreign_key(None, 'feature_type', 'placename', ['placename_id'], ['placename_id'])
    op.create_index('ix_feature_type_placename_id', 'feature_type', ['placename_id'], unique=False)
    op.create_unique_constraint('_placename_term_uc', 'feature_type', ['placename_id', 'term'])
    op.drop_index(op.f('ix_feature_type_place_id'), table_name='feature_type')
    op.drop_constraint('_place_term_uc', 'feature_type', type_='unique')
    op.drop_column('feature_type', 'place_id')
    op.create_table('placename_alt_label',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('placename_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('label', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['placename_id'], ['placename.placename_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placename_id', 'label', name='_placename_label_uc')
    )
    op.create_index('ix_placename_alt_label_placename_id', 'placename_alt_label', ['placename_id'], unique=False)
    op.create_table('placename_old_label',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('old_label_id', sa.VARCHAR(length=13), nullable=False),
    sa.Column('placename_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('rich_label', sa.VARCHAR(length=250), nullable=False),
    sa.Column('rich_date', sa.VARCHAR(length=100), nullable=True),
    sa.Column('text_date', sa.VARCHAR(length=100), nullable=True),
    sa.Column('rich_reference', sa.TEXT(), nullable=True),
    sa.Column('rich_label_node', sa.TEXT(), nullable=True),
    sa.Column('text_label_node', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['placename_id'], ['placename.placename_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('old_label_id')
    )
    op.create_index('ix_placename_old_label_placename_id', 'placename_old_label', ['placename_id'], unique=False)
    op.create_table('placename',
    sa.Column('placename_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('label', sa.VARCHAR(length=200), nullable=False),
    sa.Column('country', sa.VARCHAR(length=2), nullable=False),
    sa.Column('dpt', sa.VARCHAR(length=2), nullable=False),
    sa.Column('commune_insee_code', sa.VARCHAR(length=5), nullable=True),
    sa.Column('localization_commune_insee_code', sa.VARCHAR(length=5), nullable=True),
    sa.Column('localization_placename_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('localization_certainty', sa.VARCHAR(length=4), nullable=True),
    sa.Column('desc', sa.TEXT(), nullable=True),
    sa.Column('num_start_page', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.CheckConstraint("localization_certainty IN ('high', 'low')"),
    sa.ForeignKeyConstraint(['commune_insee_code'], ['insee_commune.insee_code'], ),
    sa.ForeignKeyConstraint(['localization_commune_insee_code'], ['insee_commune.insee_code'], ),
    sa.ForeignKeyConstraint(['localization_placename_id'], ['placename.placename_id'], ),
    sa.PrimaryKeyConstraint('placename_id')
    )
    op.create_index('ix_placename_num_start_page', 'placename', ['num_start_page'], unique=False)
    op.create_index('ix_placename_localization_placename_id', 'placename', ['localization_placename_id'], unique=False)
    op.create_index('ix_placename_localization_commune_insee_code', 'placename', ['localization_commune_insee_code'], unique=False)
    op.create_index('ix_placename_commune_insee_code', 'placename', ['commune_insee_code'], unique=False)
    op.drop_index(op.f('ix_place_old_label_place_id'), table_name='place_old_label')
    op.drop_table('place_old_label')
    op.drop_index(op.f('ix_place_alt_label_place_id'), table_name='place_alt_label')
    op.drop_table('place_alt_label')
    op.drop_index(op.f('ix_place_num_start_page'), table_name='place')
    op.drop_index(op.f('ix_place_localization_place_id'), table_name='place')
    op.drop_index(op.f('ix_place_localization_commune_insee_code'), table_name='place')
    op.drop_index(op.f('ix_place_commune_insee_code'), table_name='place')
    op.drop_table('place')
    # ### end Alembic commands ###
