"""empty message

Revision ID: 59046b1a176f
Revises: 
Create Date: 2019-04-23 10:38:49.006793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59046b1a176f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), server_default='', nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('firstname', sa.String(), server_default='', nullable=False),
    sa.Column('lastname', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_has_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_invitation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_type_placename_id'), 'feature_type', ['placename_id'], unique=False)
    op.create_index(op.f('ix_insee_commune_AR_id'), 'insee_commune', ['AR_id'], unique=False)
    op.create_index(op.f('ix_insee_commune_CT_id'), 'insee_commune', ['CT_id'], unique=False)
    op.create_index(op.f('ix_insee_commune_DEP_id'), 'insee_commune', ['DEP_id'], unique=False)
    op.create_index(op.f('ix_insee_commune_REG_id'), 'insee_commune', ['REG_id'], unique=False)
    op.create_index(op.f('ix_insee_ref_insee_code'), 'insee_ref', ['insee_code'], unique=False)
    op.create_index(op.f('ix_insee_ref_level'), 'insee_ref', ['level'], unique=False)
    op.create_index(op.f('ix_insee_ref_parent_id'), 'insee_ref', ['parent_id'], unique=False)
    op.create_index(op.f('ix_insee_ref_type'), 'insee_ref', ['type'], unique=False)
    op.create_index(op.f('ix_placename_commune_insee_code'), 'placename', ['commune_insee_code'], unique=False)
    op.create_index(op.f('ix_placename_num_start_page'), 'placename', ['num_start_page'], unique=False)
    op.create_index(op.f('ix_placename_alt_label_placename_id'), 'placename_alt_label', ['placename_id'], unique=False)
    op.create_index(op.f('ix_placename_old_label_placename_id'), 'placename_old_label', ['placename_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placename_old_label_placename_id'), table_name='placename_old_label')
    op.drop_index(op.f('ix_placename_alt_label_placename_id'), table_name='placename_alt_label')
    op.drop_index(op.f('ix_placename_num_start_page'), table_name='placename')
    op.drop_index(op.f('ix_placename_commune_insee_code'), table_name='placename')
    op.drop_index(op.f('ix_insee_ref_type'), table_name='insee_ref')
    op.drop_index(op.f('ix_insee_ref_parent_id'), table_name='insee_ref')
    op.drop_index(op.f('ix_insee_ref_level'), table_name='insee_ref')
    op.drop_index(op.f('ix_insee_ref_insee_code'), table_name='insee_ref')
    op.drop_index(op.f('ix_insee_commune_REG_id'), table_name='insee_commune')
    op.drop_index(op.f('ix_insee_commune_DEP_id'), table_name='insee_commune')
    op.drop_index(op.f('ix_insee_commune_CT_id'), table_name='insee_commune')
    op.drop_index(op.f('ix_insee_commune_AR_id'), table_name='insee_commune')
    op.drop_index(op.f('ix_feature_type_placename_id'), table_name='feature_type')
    op.drop_table('user_invitation')
    op.drop_table('user_has_role')
    op.drop_table('user_role')
    op.drop_table('user')
    # ### end Alembic commands ###
