"""empty message

Revision ID: 8f130ba1a140
Revises: dbf98328208e
Create Date: 2019-10-11 15:41:40.144832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f130ba1a140'
down_revision = 'dbf98328208e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('user_has_role')
    op.drop_table('user_invitation')
    op.drop_table('user_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('column_1', sa.INTEGER(), nullable=True)
    )
    op.create_table('user_invitation',
    sa.Column('column_1', sa.INTEGER(), nullable=True)
    )
    op.create_table('user_has_role',
    sa.Column('column_1', sa.INTEGER(), nullable=True)
    )
    op.create_table('user',
    sa.Column('column_1', sa.INTEGER(), nullable=True)
    )
    # ### end Alembic commands ###
