"""empty message

Revision ID: dbf98328208e
Revises: 59046b1a176f
Create Date: 2019-04-23 10:49:28.383121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf98328208e'
down_revision = '59046b1a176f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insee_commune', sa.Column('databnf_ark', sa.String(length=64), nullable=True))
    op.add_column('insee_commune', sa.Column('geoname_id', sa.String(length=32), nullable=True))
    op.add_column('insee_commune', sa.Column('viaf_id', sa.String(length=64), nullable=True))
    op.add_column('insee_commune', sa.Column('wikidata_item_id', sa.String(length=32), nullable=True))
    op.add_column('insee_commune', sa.Column('wikipedia_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insee_commune', 'wikipedia_url')
    op.drop_column('insee_commune', 'wikidata_item_id')
    op.drop_column('insee_commune', 'viaf_id')
    op.drop_column('insee_commune', 'geoname_id')
    op.drop_column('insee_commune', 'databnf_ark')
    # ### end Alembic commands ###
